config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  devise_for :users

  resources :games do
    resources :characters
  end

  resources :characters

end

app/models/character.rb
class Character < ActiveRecord::Base
  class << columns_hash['birthday']
    def type
      :date
    end
  end

  belongs_to :user
  belongs_to :game
  belongs_to :hobby1
  belongs_to :hobby2

  has_many :stats

  mount_uploader :image, ImageUploader

  validates :name, presence: true, uniqueness: { scope: [:user_id],
                                  message: "Character is in use." }

  validates :name, presence: true
  validates :birthday, presence: true
  validates :hobby1, presence: true
  validates :hobby2, presence: true

  def speed
    # stats.find_by(name: "speed").speed_for(birthday.month)
    if 0 < birthday.month && birthday.month < 4
      Stat::SPEED_ARRAY_1
    elsif  4 <= birthday.month && birthday.month < 7
      Stat::SPEED_ARRAY_2
    elsif  7 <= birthday.month && birthday.month < 10
      Stat::SPEED_ARRAY_3
    else
      Stat::SPEED_ARRAY_4
    end
  end

  def sanity
    if 0 < birthday.day && birthday.day < 7
      Stat::SANITY_ARRAY_1
    elsif 7 <= birthday.day && birthday.day < 15
      Stat::SANITY_ARRAY_2
    elsif 15 <= birthday.day && birthday.day < 23
      Stat::SANITY_ARRAY_3
    else
      Stat::SANITY_ARRAY_4
    end
  end

  def knowledge
    if 0 < hobby1_id && hobby1_id < 4
      Stat::KNOWLEDGE_ARRAY_1
    elsif  4 <= hobby1_id && hobby1_id < 7
      Stat::KNOWLEDGE_ARRAY_2
    elsif  7 <= hobby1_id && hobby1_id < 10
      Stat::KNOWLEDGE_ARRAY_3
    else
      Stat::KNOWLEDGE_ARRAY_4
    end
  end

  def might
    if 0 < hobby2_id && hobby2_id < 4
      Stat::MIGHT_ARRAY_1
    elsif  4 <= hobby2_id && hobby2_id < 7
      Stat::MIGHT_ARRAY_2
    elsif  7 <= hobby2_id && hobby2_id < 10
      Stat::MIGHT_ARRAY_3
    else
      Stat::MIGHT_ARRAY_4
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :characters
  accepts_nested_attributes_for :characters

  validates :name, presence: true
end

app/models/hobby1.rb
class Hobby1 < ActiveRecord::Base
  has_many :characters

  validates :name, presence: true
end

app/models/hobby2.rb
class Hobby2 < ActiveRecord::Base
  has_many :characters

  validates :name, presence: true
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :character
  STAT_TYPES = ["speed","might","knowledge","sanity"]

  # validates :name, presence: true
  # validates :character_id, presence: true
  # validates :value, presence: true
  # validates :level, presence: true

  SPEED_ARRAY_1 = [0, 2, 3, 3, 4, 5, 6, 7, 7]
  SPEED_ARRAY_2 = [0, 3, 4, 4, 4, 5, 6, 7, 8]
  SPEED_ARRAY_3 = [0, 3, 3, 4, 5, 6, 6, 7, 8]
  SPEED_ARRAY_4 = [0, 4, 4, 4, 5, 6, 7, 7, 8]

  SANITY_ARRAY_1 = [0, 2, 3, 3, 4, 5, 6, 7, 7]
  SANITY_ARRAY_2 = [0, 3, 4, 4, 4, 5, 6, 7, 8]
  SANITY_ARRAY_3 = [0, 3, 4, 5, 5, 6, 6, 7, 8]
  SANITY_ARRAY_4 = [0, 4, 4, 4, 5, 6, 7, 7, 8]

  KNOWLEDGE_ARRAY_1 = [0, 2, 3, 3, 4, 5, 6, 7, 7]
  KNOWLEDGE_ARRAY_2 = [0, 3, 4, 4, 4, 5, 6, 7, 8]
  KNOWLEDGE_ARRAY_3 = [0, 3, 4, 5, 5, 6, 6, 7, 8]
  KNOWLEDGE_ARRAY_4 = [0, 4, 4, 4, 5, 6, 7, 7, 8]

  MIGHT_ARRAY_1 = [0, 2, 3, 3, 4, 5, 6, 7, 7]
  MIGHT_ARRAY_2 = [0, 3, 4, 4, 4, 5, 6, 7, 8]
  MIGHT_ARRAY_3 = [0, 3, 4, 5, 5, 6, 6, 7, 8]
  MIGHT_ARRAY_4 = [0, 4, 4, 4, 5, 6, 7, 7, 8]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :require_login, only: [:new, :edit, :update, :delete]

  def index
    @characters = Character.all
    @character = Character.new
  end

  def create

  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    @character.user_id = current_user.id
    if @character.save
      flash[:notice] = "Character created!"
      redirect_to games_path
    else
      flash[:notice] = @character.errors.full_messages.join(". ")
      render 'new'
    end
  end

  def show
    @character = Character.find(params[:id])
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    if @character.update(character_params)
      flash[:notice] = "Character Updated!"
      redirect_to :back
    else
      flash[:notice] = @character.errors.full_messages.join(" ")
      render 'show'
    end
  end

  def destroy
    @character = Character.find(params[:id])
    Character.destroy(@character)

    flash[:notice] = 'Character Deleted'
    redirect_to characters_path
  end

  protected

  def character_params
    params.require(:character).permit(
                                      :id,
                                      :name,
                                      :user_id,
                                      :game_id,
                                      :birthday,
                                      :hobby1_id,
                                      :hobby2_id,
                                      :image
                                      )
  end

  def character_update_params
    params.permit( :id, :game_id)
  end

  private

  def require_login
    unless user_signed_in?
      flash[:error] = "You must be signed in to do that"
      redirect_to new_user_session_path
    end
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_login, only: [:new, :edit, :update, :delete]

  def index
    @games = Game.all.order(created_at: :desc)
    @game = Game.new
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:notice] = "Game created!"
      redirect_to games_path
    else
      flash[:notice] = @game.errors.full_messages.join(". ")
      render new
    end
  end

  def show
    @game = Game.find(params[:id])
    @characters = Character.where(game: nil)
    @character = Character.new
  end

  def update
    @game = Game.id
    @character.game = @game
  end

  protected

  def game_params
    params.require(:game).permit(:id, :name)
  end

  private

  def require_login
    unless user_signed_in?
      flash[:error] = "You must be signed in to do that"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/views/characters/edit.html.erb
<div class="small-6 columns small-centered columns">
  <h1> Edit Your Character </h1>
  <%= form_for @character do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :birthday, "Birthday" %>
    <%= f.date_select :birthday , start_year: 1910 %>

    <%= f.label :hobby1_id %>
    <%= f.select :hobby1_id, Hobby1.all.collect{|h| [h.name, h.id]}%>

    <%= f.label :hobby2_id %>
    <%= f.select :hobby2_id, Hobby2.all.collect{|h| [h.name, h.id]}%>

    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.submit "Save changes", class: "button tiny" %>
  <% end %>
</div>

app/views/characters/index.html.erb
<div class="small-12 small-centered columns">
  <h1> My Characters</h1>
  <% @characters.each do |char| %>
    <div class="small-3 medium-4 columns"
    <% if char.user_id == current_user.id %>
    <div class="name">
      <h3><%= link_to char.name, character_path(char) %></h3>
    </div>
      <% if user_signed_in? && (current_user == char.user) %>
            <div class="button small"><%= link_to "Delete", character_path(char), method: :delete %></div>
            <% if current_user == char.user %>
              <div class="button small"><%= link_to "Edit", edit_character_path(char) %></div>
              <br>
            </div>
            <% end %>
          <% end %>
    <% end %>
  <% end %>
</div>

app/views/characters/new.html.erb
<div class="small-6 small-centered columns">
  <h1> Create a Character </h1>
  <%= form_for @character do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
<div class="dropdown-inline-display">
    <%= f.label :birthday, "Birthday" %>
    <%= f.date_select :birthday , start_year: 1910 %>
</div>
    <%= f.label :hobby1_id %>
    <%= f.select :hobby1_id, Hobby1.all.collect{|h| [h.name, h.id]}%>

    <%= f.label :hobby2_id %>
    <%= f.select :hobby2_id, Hobby2.all.collect{|h| [h.name, h.id]}%>

    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.submit "Submit", class: "button tiny" %>
  <% end %>
</div>

<% if false %>
<div>
  <!-- Upload image -->
<section id="sectionDragAndDrop">
    <div class="drop" id="drop">
        <p>Drag & drop or click here to upload an image.</p>
    </div>
    <input class="file-upload hidden" id="fileUpload" type="file">
</section>

<!-- Resize image -->
<section class="hidden" id="sectionResize">
    <div class="image-resize" id="imageResize"></div>
  <button class="btn" id="crop"><span class='fa fa-crop'></span> Crop</button>
</section>

<!-- Insert thumbnail -->
<section class="hidden" id="sectionThumbnail">
    <div class="thumbnail" id="thumbnail"></div>
</section>
</div>
<h1>Image Crop</h1>

<img id="exampleImage" src="http://i.imgur.com/dBpMbIf.jpg" crossorigin="Anonymous">

<button class="btn" id="exampleCrop">Crop</button>
</div>
<% end %>

app/views/characters/show.html.erb
<div class="small-12 small-centered columns">
  <div>
    <h1><%= @character.name %></h1>
    <h2>
      Birthday: <%= @character.birthday.month %>/
      <%= @character.birthday.day %> •
      Hobbies: <%= @character.hobby1.name %> and
      <%= @character.hobby2.name %>
  </div>
</div>

<div class="small-6 columns">
  <div class="stat-bubble">
    <h3> Speed <% @character.speed.each do |stat| %> </h3>
    <ul class="stat-labels nine-columns">
        <li> <%= stat %> </li>
      <% end %>
    </ul>
  </div>

  <div class="stat-bubble">
    <h3> Might <% @character.might.each do |stat| %> </h3>
    <ul class="stat-labels nine-columns">
        <li> <%= stat %> </li>
      <% end %>
    </ul>
  </div>

  <div class="stat-bubble">
    <h3> Sanity <% @character.sanity.each do |stat| %> </h3>
    <ul class="stat-labels nine-columns">
        <li> <%= stat %> </li>
      <% end %>
    </ul>
  </div>

  <div class="stat-bubble">
    <h3> Knowledge <% @character.knowledge.each do |stat| %> </h3>
    <ul class="stat-labels nine-columns">
        <li> <%= stat %> </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="small-6 columns">
  <div class="character-pic">
    <%= image_tag @character.image_url.to_s %>
  </div>
</div>

app/views/games/index.html.erb
<div class="home-header">
  <div class="small-5 columns small-offset-6 columns ">
    <div class="about">
        <p>
          SpookyHouse is a character compainion for the board game
        <a href="http://www.wizards.com/default.asp?x=ah/prod/betrayalhouse">
          Betrayal at the House on the Hill</a>. Forget the cardboard cards
          and create your own character to spice up your game play.  Join a
          game with your friends to check out where the other characters
          stand.
        </p>
        <%= link_to "Create a new game", new_game_path(@game), class: "button small" %>
        <%= link_to "Create a new character", new_character_path, class: "button small" %>
    </div>
  </div>
</div>
<div class="joingame">
  <div class="medium-8 columns">
  <% @games.each do |game| %>
    <div class="small-6 medium-2 columns gameblock">
      <p class="text-center">
          <%= link_to game.name, game_path(game) %>
        </p>
    </div>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div class="small-6 columns small-centered columns">
  <h2> Create a new game </h2>
  <%= form_for @game do |f| %>

    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.submit "Submit", class: "button tiny" %>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="small-6 small-centered columns">
  <h1><%= @game.name %></h1>
</div>
<div class="small-6 columns">
  <div>
    <h2>Pick a character!</h2>
    <h3>
      <% @characters.each do |char| %>
      <%= link_to char.name, game_character_path(
          @game, char, character:{game_id: @game.id }
        ), method: :patch, class: "button small" %>
      <% end %>
    </h3>

  </div>
</div>
  <% if !@game.characters.nil? && !@game.characters.empty? %>
  <div class="small-6 columns">
    <div class="players">
    <h3>Current Players</h3>
    <% @game.characters.each do |char| %>
      <%= link_to char.name, character_path(char) %><br>
    <% end %>
  <% end %>
  </div>

  <div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Google Fonts Oswald -->
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700' rel='stylesheet' type='text/css'>

  <title>SpookyHouse</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "vendor/modernizr" %>
</head>
<body>
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">SpookyHouse</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to "Create a New Character", new_character_path %></li>
          <li class="divider"></li>
          <li><%= link_to "My Characters", characters_path %></li>
          <li class="divider"></li>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li class="divider"></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>
  <%- flash.each do |key, value| -%>
     <div data-alert class="alert-box">
       <div class="flash flash-<%= key %>">
         <%= value %>
       </div>
       <a href="#" class="close">&times;</a>
       </div>
     <%- end -%>
     
      <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>